### ISSUE TITLE
Consider creating an organization

### ISSUE THREAD

**Issue by MaxAtoms** [DotNetKoans/DotNetKoans#171]
Using a GitHub organization would allow to appoint multiple owners.
This could help in reviving the project and keeping it up-to-date.

**Comment by NotMyself** [comment]
Hi @MaxAtoms, post octoberfest we can discuss this along with you taking over maintaining the project.

**Comment by MaxAtoms** [comment]
From my side, yes. I am open to discuss this.
Here is the related documentation on how to transfer a repo:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository
I could create the organization.

**Comment by NotMyself** [comment]
So I wrote a blog post about how this project got started. You can find it [here](https://iamnotmyself.com/learn-c-on-windows-osx-or-linux-with-the-net-core-koans-2/). As you can see, the original idea belonged to [Jim Weirich](https://en.wikipedia.org/wiki/Jim_Weirich) and the initial .NET version was by @coryfoy. I took Cory's work and got it running in .net core and made some other additions. 

All I ask by a new maintainer is that Jim feature heavily in discussions/documentation of it and Cory and I are credited for our efforts as long as the project exists.

If you are agreeable, I am happy to hand the reins over to you.

**Comment by CoryFoy** [comment]
@NotMyself Thank you for the mention and credits, especially to Jim. I'm happy that original project still has value to people!

**Comment by MaxAtoms** [comment]
@NotMyself I am very happy to oblige to keep and highlight these acknowledgments.

You should have received an invitation to join the newly created organization as a second owner. That means that you will not be giving up the reigns completely. Rather, we will both have the same control over the project.

When you find the time, you can then import the repository: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

@CoryFoy If we find that a GitHub organization is the right structure to maintain the .NET Koans, we could also talk about importing your existing koans, if you are open for this discussion. However, I would do that at a later point and first collect some experience with only this one repo.

Thinking about it, it might actually make sense to rename the DotNetKoans (formerly DotNetCoreKoans) again when importing them into the organization. If we rename them to `CsharpKoans`, we could at a later point have `VisualBasicKoans` and maybe even `FsharpKoans` under the umbrella of the organization. That is an idea I just had, though.

**Comment by NotMyself** [comment]
And done.

**Comment by CoryFoy** [comment]
@MaxAtoms More than happy for them to be there if they're useful! No rush - just let me know whatever it is you all need once you get up and running.
